# Generated by Django 6.0.4 on 2026-05-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model/Project name', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='One-line summary for listing cards', max_length=300)),
                ('description', models.TextField(help_text='Detailed description (Markdown)')),
                ('paper_title', models.CharField(blank=True, max_length=500)),
                ('paper_url', models.URLField(blank=True, help_text='arXiv / journal URL')),
                ('paper_doi', models.CharField(blank=True, max_length=100)),
                ('authors', models.TextField(blank=True, help_text='Comma-separated')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('huggingface_url', models.URLField(blank=True)),
                ('model_type', models.CharField(choices=[('foundation', 'Foundation Model'), ('geneformer', 'Geneformer-like'), ('virtual_cell', 'Virtual Cell'), ('multimodal', 'Multi-modal'), ('spatial', 'Spatial'), ('perturbation', 'Perturbation'), ('generative', 'Generative'), ('other', 'Other')], default='other', max_length=20)),
                ('modality', models.CharField(choices=[('scrna', 'scRNA-seq'), ('scatac', 'scATAC-seq'), ('multiome', 'Multiome'), ('spatial', 'Spatial'), ('citeseq', 'CITE-seq'), ('other', 'Other')], default='scrna', max_length=20)),
                ('architecture', models.CharField(blank=True, max_length=200)),
                ('pretraining_data', models.CharField(blank=True, help_text='Pretraining datasets used', max_length=500)),
                ('parameter_count', models.CharField(blank=True, help_text='e.g. "300M", "6.5B"', max_length=50)),
                ('embedding_dim', models.IntegerField(blank=True, null=True)),
                ('context_length', models.IntegerField(blank=True, help_text='Max input tokens/cells', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional figure/image URL')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='scmodels_app.tag')),
            ],
            options={
                'verbose_name_plural': 'Model Entries',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
