# Generated by Django 6.0.4 on 2026-05-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmodels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelentry',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image (shown on detail page and card)', null=True, upload_to='models/covers/'),
        ),
    ]
