# Generated by Django 6.0.4 on 2026-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmodels_app', '0003_resourcecategory_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Full-width background image for the category detail page', null=True, upload_to='categories/backgrounds/'),
        ),
    ]
