# Generated by Django 6.0.4 on 2026-05-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmodels_app', '0004_resourcecategory_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelentry',
            name='wechat_article_title',
            field=models.CharField(blank=True, help_text='Display title for the WeChat article link', max_length=300),
        ),
        migrations.AddField(
            model_name='modelentry',
            name='wechat_article_url',
            field=models.URLField(blank=True, help_text='Link to WeChat public account科普推文 (mp.weixin.qq.com)'),
        ),
    ]
