# Generated by Django 6.0.4 on 2026-05-12 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='analysis/uploads/')),
                ('original_filename', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('min_genes', models.IntegerField(default=200, help_text='Min genes per cell')),
                ('min_cells', models.IntegerField(default=3, help_text='Min cells per gene')),
                ('n_top_genes', models.IntegerField(default=2000, help_text='HVGs')),
                ('n_neighbors', models.IntegerField(default=15)),
                ('resolution', models.FloatField(default=0.8)),
                ('n_markers', models.IntegerField(default=10, help_text='Top markers per cluster')),
                ('n_cells', models.IntegerField(blank=True, null=True)),
                ('n_genes', models.IntegerField(blank=True, null=True)),
                ('n_clusters', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
